server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  webflux:
    csrf:
      enabled: false
  application:
    name: gateway-service
  jwt:
    accessTokenValidityInMilliseconds: 3600000
    refreshTokenValidityInMilliseconds: 43200000
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**,/api/delivery-users/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: hubs-service
          uri: lb://hubs-service
          predicates:
            - Path=/hubs/**,/hub-routes/**
        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/companies/**,/products/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/api/slack/**

        - id: order-service-swagger
          uri: lb://order-service
          predicates:
            - Path=/order-service/v3/api-docs/**
          filters:
            - RewritePath=/order-service(?<segment>/?.*), $\{segment}

        - id: message-service-swagger
          uri: lb://message-service
          predicates:
            - Path=/message-service/v3/api-docs/**
          filters:
            - RewritePath=/message-service(?<segment>/?.*), $\{segment}

        - id: user-service-swagger
          uri: lb://user-service
          predicates:
            - Path=/user-service/v3/api-docs/**
          filters:
            - RewritePath=/user-service(?<segment>/?.*), $\{segment}

        - id: hubs-service-swagger
          uri: lb://hubs-service
          predicates:
            - Path=/hubs-service/v3/api-docs/**
          filters:
            - RewritePath=/hubs-service(?<segment>/?.*), $\{segment}

        - id: company-service-swagger
          uri: lb://company-service
          predicates:
            - Path=/company-service/v3/api-docs/**
          filters:
            - RewritePath=/company-service(?<segment>/?.*), $\{segment}

        - id: swagger-ui
          uri: lb://user-service
          predicates:
            - Path=/swagger-ui/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
        add-to-simple-url-handler-mapping: true

      discovery:
        locator:
          enabled: true
  zipkin:
    base-url: http://zipkin:9411
    sender:
      type: web
tracing:
  sampling:
    probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
service:
  jwt:
    secret-key: L@4mV9eZ*R1z#3Tq6!P5jY2wF8xL7d$Q9%kH1xA6^bL0*H4mJ9!nT3zP6q^Y8uB7#xJ2vM4@fH5cT3r!D6sN+2NE1
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    reactor.netty: DEBUG
    com._hateam: TRACE
management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Order Service
        url: /order-service/v3/api-docs
      - name: Message Service
        url: /message-service/v3/api-docs
      - name: User Service
        url: /user-service/v3/api-docs
      - name: Hubs Service
        url: /hubs-service/v3/api-docs
      - name: Company Service
        url: /company-service/v3/api-docs